# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  heroku: circleci/heroku@2.0.0
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - deploy:
        executor: heroku/default
        steps:
          - checkout
          - heroku/install
          - run:
              command: >
                echo "The command above installs Heroku, the command below deploys.
                What you do inbetween is up to you!"
          - heroku/deploy-via-git
    workflows:
      heroku_deploy:
        jobs:
          - deploy
